### ISSUE TITLE
[$rootScope:infdig] and multiple http calls when using with angular 1.4.8

### ISSUE THREAD

**Issue by egore** [angular-ui/ui-calendar#364]
I can't seem to use ui-calendar with angular 1.4.8. It causes an error in the log, calls the eventSource multiple times and also adds the events to often to the calendar.

I created a jsfiddle showing the issue:

https://jsfiddle.net/0gb2cd96/2/

The error log is:
```
Error: [$rootScope:infdig] http://errors.angularjs.org/1.4.8/$rootScope/infdig?p0=10&p1=%5B%5B%7B%22ms…urn%20g%7D%22%2C%22newVal%22%3A%5B20%5D%2C%22oldVal%22%3A%5B18%5D%7D%5D%5D
    at Error (native)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:6:416
    at r.$digest (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:131:499)
    at r.$apply (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:134:78)
    at https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:20:59
    at Object.e [as invoke] (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:39:394)
    at c (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:19:482)
    at yc (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:20:274)
    at Zd (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:19:83)
    at HTMLDocument.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.8/angular.min.js:294:192)
```

**Comment by sanitar4eg** [comment]
I have some problem
Please tell me solution, if you resolve this.
